# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Auto-generated Dockerfile for Alibaba Cloud Ops MCP Server
FROM python:3.11-slim

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project metadata and README files required for packaging
COPY pyproject.toml README.md README_zh.md ./

# Copy source code
COPY src ./src

# Install Python dependencies and the MCP server
RUN pip install --no-cache-dir .

# Default entrypoint
ENTRYPOINT ["alibaba-cloud-ops-mcp-server"]
